Node-RED: bugfixes and feature enhancements
- Fixed the error: TypeError: console.err is not a function (user-authentication.js)
- We use tabs for indenting, so replaced the spaces with tabs
  (start-node-red.sh)
- Moved the user-authentication.js file to the rootfs (node-red_2.0.5.bb). This
  removes the requirement for the npm modules bcryptjs and debug to be installed
  in the ~/.node-red directory (as it now uses the node-red provided modules).
- Modified settings.js to point to the new location of user-authentication.js
- Adjusted the call '*** Starting node-red ***' to '*** Starting node-red
  script ***', because this is slightly less confusing when used interactively
  for generating hashed passwords (node-red admin hash-pw). See:
  https://nodered.org/docs/user-guide/runtime/securing-node-red
- Accept parameters (eg --safe) to passthrough to the node-red javascript file
  (start-node-red.sh)
- Prepare for moving the data of node-red to another location on filesystem by
  adding the --userDir to the node-red call (start-node-red.sh).
- Updated the npm-shrinkwrap.json file to correspond with the 2.0.5 Node-RED
  version